#index:
#    path: /
#    controller: App\Controller\DefaultController::index

controllers:
    resource: '../src/Controller/'
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"