_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

controllers:
    resource: '../src/Controller/'
    type:     annotation

profil_edited:
    path: /profile/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fos_user_profile_edit
        permanent: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"