controllers:
    resource: '../src/Controller/'
    type:     annotation

user_list:
    path: /
    controller: App\Controller\UserController::index

profil_edited:
    path: /profile/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fos_user_profile_edit
        permanent: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
