_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

controllers:
    resource: '../src/Controller/'
    type:     annotation

profile_edited:
    path: /profile/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fos_user_profile_edit
        permanent: true

profile_edit:
    path: /profile/edit
    controller: App\Controller\ProfileController:editAction

user_authentified:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: user_list
        permanent: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

core_sphere_console:
    resource: .
    type: extra